### ISSUE TITLE
fix display emojiicon as default

### ISSUE THREAD

**Issue by xShut** [rakugoteam/Emojis-For-Godot#13] opened 2023-11-03 15:01 UTC
to fix display emoji need to add a func _ready with first method 

```
func _ready():
	_set_emoji(emoji_name)
```

it will fix the display as startup and will be display as default :sunglasses:

**Comment by Jeremi360** [comment] 2023-11-05 07:10
@xShut I'm not sure what error is ? 
You mean that EmojiIcon doesn't display its emoji on app start ?
I think it was already fixed with #11 , but I was not aware of this existence, 
as seen in this screenshot, emojis appear in both the editor and the runtime.
![image](https://github.com/rakugoteam/Emojis-For-Godot/assets/1294815/425246e1-69e3-4021-ad72-1c9028e9bd9e)

Try to download the code directly from the repo and check if the problem is still.
![image](https://github.com/rakugoteam/Emojis-For-Godot/assets/1294815/65105eda-0437-43d7-908d-05814c12358d)

**Closed as completed** 2023-11-11 12:06 UTC
Labels: bug
